export const GET_DEALS_REQUEST = 'GET_DEALS_REQUEST'
export const GET_DEALS_SUCCESS = 'GET_DEALS_SUCCESS'
export const GET_DEALS_FAIL = 'GET_DEALS_FAIL'

export const ADD_DEAL_REQUEST = 'ADD_DEAL_REQUEST'
export const ADD_DEAL_SUCCESS = 'ADD_DEAL_SUCCESS'
export const ADD_DEAL_FAIL = 'ADD_DEAL_FAIL'

export const REMOVE_DEAL_REQUEST = 'REMOVE_DEAL_REQUEST'
export const REMOVE_DEAL_SUCCESS = 'REMOVE_DEAL_SUCCESS'
export const REMOVE_DEAL_FAIL = 'REMOVE_DEAL_FAIL'

export const EDIT_DEAL_REQUEST = 'EDIT_DEAL_REQUEST'
export const EDIT_DEAL_SUCCESS = 'EDIT_DEAL_SUCCESS'
export const EDIT_DEAL_FAIL = 'EDIT_DEAL_FAIL'