export const GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST'
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS'
export const GET_BANNERS_FAIL = 'GET_BANNERS_FAIL'

export const EDIT_BANNERS_REQUEST = 'EDIT_BANNERS_REQUEST'
export const EDIT_BANNERS_SUCCESS = 'EDIT_BANNERS_SUCCESS'
export const EDIT_BANNERS_FAIL = 'EDIT_BANNERS_FAIL'