export const GET_HSN_REQUEST = 'GET_HSN_REQUEST'
export const GET_HSN_SUCCESS = 'GET_HSN_SUCCESS'
export const GET_HSN_FAIL = 'GET_HSN_FAIL'

export const EDIT_HSN_REQUEST = 'EDIT_HSN_REQUEST'
export const EDIT_HSN_SUCCESS = 'EDIT_HSN_SUCCESS'
export const EDIT_HSN_FAIL = 'EDIT_HSN_FAIL'

export const ADD_HSN_REQUEST = 'ADD_HSN_REQUEST'
export const ADD_HSN_SUCCESS = 'ADD_HSN_SUCCESS'
export const ADD_HSN_FAIL = 'ADD_HSN_FAIL'

export const DELETE_HSN_REQUEST = 'DELETE_HSN_REQUEST'
export const DELETE_HSN_SUCCESS = 'DELETE_HSN_SUCCESS'
export const DELETE_HSN_FAIL = 'DELETE_HSN_FAIL'